### ISSUE TITLE
Any reason `srcDirs += protop.path` and `task.dependsOn { protopSync }` aren't done automatically by the plugin?

### ISSUE THREAD

**Issue by noel-yap** [protop-io/protop-gradle-plugin#1]
I'm thinking if these were done automatically by the plugin, it'd be easier to use and would clean up the build file.

Is there some technical reason or purposeful design decision these aren't being done automatically?

**Comment by jefferyshivers** [comment]
I like that idea much better, especially as these will likely never be different! Any interest in putting up a PR for this?

**Comment by noel-yap** [comment]
Sure thing.

**Comment by noel-yap** [comment]
https://github.com/protop-io/protop-gradle-plugin/pull/3
